export const environment = {
  production: true,
  rootUrl: "http://localhost:8090/api/auth",  //url in use
    baseUrl: "http://localhost:8090/api/test",
    gateUrl: "http://localhost:8090/api",
    lineUrl: "http://localhost:8090/api/admin",
    ptoUrl: "http://localhost:8090/api/auth",
    ptoListUrl: "http://localhost:8090/vendor",
    ptoIdUrl: "http://localhost:8090/vendor",
    userlist: "http://localhost:8090/api/activeuser",
    configUrl: "http://localhost:8090/api",
    complainListUrl: "http://localhost:8090/api",
    mailUrl: "http://localhost:8090/sendMail",
    alarmUrl: "http://localhost:8090/api/alarm",
    dbUrl: "http://localhost:8090/api",
    eventUrl: "http://localhost:8090/api",
    ntpUrl: "http://localhost:8090/api",
    transactionUrl: "http://localhost:8090/api",
    generalmsgUrl: "http://localhost:8090/api",
    maintenanceStaffListUrl: "http://localhost:8090/api",
    productUrl: "http://localhost:8090/api/afc", // url in use
    equipmentUrl: "http://localhost:8090/api/equipment",
    productById: "http://localhost:8090/api/singleinventory",
    equipmentByUrl: "http://localhost:8090/api/singleequipment",
    directionUrl: "http://localhost:8090/api/gatedirection",
    stationGateDir: "http://localhost:8090/api/direction",
    terminalUrl: "http://localhost:8090/api/terminal",
    createUserUrl: "http://localhost:8090/api/createuser/add",
    assignUserURL: "http://localhost:8090/api/usertostation",
    CSV__URL: "http://localhost:8090/api",
    BASEURL: "http://localhost:8090"
};
